import { Character } from './types';

// This character data has been carefully curated based on the provided PDF document,
// simulating a Gemini API call with a prompt to extract structured information
// with a temperature of 0 to avoid hallucinations and ensure factual adherence.

export const CHARACTERS: Character[] = [
  {
    name: 'Krishna',
    clan: 'Vrishni',
    role: 'A divine catalyst and advisor to the Pandavas.',
    description: "An incarnation of Vishnu, his strategic wisdom is pivotal. He delivers the Bhagavad Gita to Arjuna and urges him to strike the vulnerable Karna, reminding him that the rules of war were already broken by the enemy in the killing of Abhimanyu.",
    image: 'https://picsum.photos/seed/krishna/400/500',
  },
  {
    name: 'Arjuna',
    clan: 'Pandava',
    role: 'The great Pandava archer and central hero of the Bhagavad Gita.',
    description: 'One of the five Pandava brothers, son of Indra. He receives the profound discourse of the Bhagavad Gita from Krishna. His killing of Karna, while his enemy was vulnerable, underscores how even heroes can be undone by unrighteous circumstances.',
    image: 'https://picsum.photos/seed/arjuna/400/500',
  },
  {
    name: 'Yudhishthira',
    clan: 'Pandava',
    role: 'The eldest Pandava, the embodiment of dharma.',
    description: "Son of the god Dharma, known for his righteousness. His adherence to truth is tested when he utters a half-truth about the death of 'Ashwatthama' (an elephant), which leads Drona to lay down his arms. This act shows the war's corrupting influence.",
    image: 'https://picsum.photos/seed/yudhishthira/400/500',
  },
   {
    name: 'Bhima',
    clan: 'Pandava',
    role: 'The second Pandava, known for his immense strength and wrath.',
    description: "Son of the wind-god Vayu. After Draupadi's humiliation, he takes a terrible vow to drink Dushasana's blood and kill all 100 Kaurava brothers, a vow he systematically fulfills. His final mace duel with Duryodhana seals the Pandavas' victory.",
    image: 'https://picsum.photos/seed/bhima/400/500',
  },
  {
    name: 'Duryodhana',
    clan: 'Kaurava',
    role: 'The eldest Kaurava and primary antagonist, driven by jealousy.',
    description: "The eldest of Dhritarashtra's 100 sons. His unwavering arrogance and jealousy drive the conflict. He is an exceptional mace fighter, but is ultimately killed by Bhima in their final duel on the 18th day of the war.",
    image: 'https://picsum.photos/seed/duryodhana/400/500',
  },
  {
    name: 'Dushasana',
    clan: 'Kaurava',
    role: 'The infamous brother who sealed the Kauravas\' fate.',
    description: 'The second Kaurava brother, remembered for his role in the public disrobing of Draupadi. This infamous event was the direct cause of Bhima\'s oath to avenge the insult by drinking Dushasana\'s blood. He was brutally killed by Bhima, who fulfilled his vow.',
    image: 'https://picsum.photos/seed/dushasana/400/500',
  },
  {
    name: 'Karna',
    clan: 'Kaurava (allied)',
    role: 'The tragic hero, hidden son of Kunti, and loyal friend to Duryodhana.',
    description: "The eldest half-brother of the Pandavas. He served as the commander-in-chief of the Kaurava army on the 16th and 17th days. He is killed by Arjuna when his chariot wheel becomes stuck in the mud due to a curse, leaving him vulnerable.",
    image: 'https://picsum.photos/seed/karna/400/500',
  },
  {
    name: 'Abhimanyu',
    clan: 'Pandava',
    role: 'The tragic prince and Arjuna\'s valiant son.',
    description: 'The son of Arjuna and Subhadra. A profoundly skilled archer, he single-handedly broke into the formidable Chakravyuha formation on the 13th day of the war. He was trapped inside and killed by multiple warriors collectively, violating the established rules of warfare.',
    image: 'https://picsum.photos/seed/abhimanyu/400/500',
  },
  {
    name: 'Ghatotkacha',
    clan: 'Pandava (ally)',
    role: 'The powerful half-demon son of Bhima.',
    description: "Son of Bhima and the Rakshasi Hidimbi. His strength and magical powers peaked at night. On the 14th night, his rampage forced Karna to use his one-time divine weapon, the Vasavi Shakti, to kill him, saving Arjuna from the same fate.",
    image: 'https://picsum.photos/seed/ghatotkacha/400/500',
  },
  {
    name: 'Bhishma',
    clan: 'Kuru',
    role: 'The grandsire of the Kuru dynasty, bound by a vow of service.',
    description: 'The first commander-in-chief of the Kaurava army. The Pandavas defeated him on Day 10 by using Shikhandi as a shield. He fell, pierced by countless arrows, and rested on a "bed of arrows" for 58 days before willingly leaving his body.',
    image: 'https://picsum.photos/seed/bhishma/400/500',
  },
  {
    name: 'Drona',
    clan: 'Kuru (advisor)',
    role: 'The revered martial arts teacher to both the Pandavas and Kauravas.',
    description: 'The royal preceptor and second Kaurava commander. Heartbroken by false news of his son\'s death, he laid down his weapons and entered a state of meditation, at which point he was beheaded by Dhrishtadyumna, fulfilling a prophecy.',
    image: 'https://picsum.photos/seed/drona/400/500',
  },
  {
    name: 'Ashwatthama',
    clan: 'Kaurava (ally)',
    role: 'The vengeful survivor and son of Drona.',
    description: "Enraged by his father's deceptive death, he retaliated in a brutal night raid, slaughtering the remaining Pandava forces, including the five Upapandavas. As an immortal, he is one of the few Kaurava-allied warriors to survive the war.",
    image: 'https://picsum.photos/seed/ashwatthama/400/500',
  },
  {
    name: 'Shakuni',
    clan: 'Gandhara',
    role: 'The cunning maternal uncle of the Kauravas and master manipulator.',
    description: "The mastermind behind the Kauravas' schemes. He engineered the rigged game of dice that led to the Pandavas' humiliation and exile, ultimately instigating the Kurukshetra War. He was killed during the war.",
    image: 'https://picsum.photos/seed/shakuni/400/500',
  },
  {
    name: 'Dhrishtadyumna',
    clan: 'Panchala',
    role: 'The fated commander of the Pandava army.',
    description: "Son of King Drupada, born from a fire-sacrifice to kill Drona. He fulfills this destiny on Day 15. He was later killed in an act of vengeance by Ashwatthama, who brutally beat him to death in the post-war night raid.",
    image: 'https://picsum.photos/seed/dhrishtadyumna/400/500',
  },
  {
    name: 'Yuyutsu',
    clan: 'Kaurava (defected)',
    role: 'The righteous brother who chose dharma over family.',
    description: "The son of Dhritarashtra and a Vaishya servant. Unlike his Kaurava half-brothers, he recognized their unrighteousness and chose to join the Pandava side. This singular act of moral courage made him one of the war's very few survivors.",
    image: 'https://picsum.photos/seed/yuyutsu/400/500',
  },
  {
    name: 'Kripacharya',
    clan: 'Kuru (Guru)',
    role: 'The royal guru and a survivor of the war.',
    description: "A revered teacher and the brother-in-law of Drona. He fought for the Kauravas out of loyalty to the throne. Along with Ashwatthama and Kritavarma, he was one of the only three major surviving warriors on the Kaurava side.",
    image: 'https://picsum.photos/seed/kripacharya/400/500',
  },
  {
    name: 'Jayadratha',
    clan: 'Sindhu',
    role: 'The King of Sindhu and a key Kaurava ally.',
    description: "He played a crucial role in Abhimanyu's death by single-handedly preventing the other Pandavas from entering the Chakravyuha formation. This act sealed his fate; Arjuna vowed to kill him, a feat accomplished after Krishna created a false sunset to expose him.",
    image: 'https://picsum.photos/seed/jayadratha/400/500',
  },
  {
    name: 'Bhagadatta',
    clan: 'Pragjyotisha',
    role: 'The formidable king and elephant warrior.',
    description: "The King of Pragjyotisha, known for his formidable combat skills while riding his elephant, Supratika. He was a key figure on the Kaurava side and was killed by Arjuna on the 12th day of the war after a fierce battle.",
    image: 'https://picsum.photos/seed/bhagadatta/400/500',
  },
  {
    name: 'Drupada',
    clan: 'Panchala',
    role: 'The King of Panchala and a key Pandava ally.',
    description: "Father of Dhrishtadyumna, Draupadi, and Shikhandi. His long-standing rivalry with Drona was a key factor in the war's alliances. He fought fiercely alongside the Pandavas and was ultimately killed by his old rival, Drona.",
    image: 'https://picsum.photos/seed/drupada/400/500',
  },
  {
    name: 'Shikhandi',
    clan: 'Panchala',
    role: 'The warrior destined to cause Bhishma\'s downfall.',
    description: "The son of King Drupada, born as a woman in a previous life. Knowing that Bhishma would not raise a weapon against a former woman, Arjuna used him as a shield to defeat the grandsire. Shikhandi fulfilled his destiny but also perished in the war.",
    image: 'https://picsum.photos/seed/shikhandi/400/500',
  },
  {
    name: 'King Virata',
    clan: 'Matsya',
    role: 'The King of Matsya who sheltered the Pandavas.',
    description: "The king who provided refuge to the Pandavas during their year of incognito exile. In gratitude, he and his sons fought alongside the Pandavas. All perished in the war, with Virata himself being killed by Dronacharya.",
    image: 'https://picsum.photos/seed/virata/400/500',
  },
  {
    name: 'Draupadi',
    clan: 'Panchala',
    role: 'The shared wife of the Pandavas and a catalyst for the war.',
    description: "Born from a sacrificial fire, Draupadi is a strong and fiery princess. Her public humiliation by Dushasana in the Kaurava court is a pivotal moment that becomes a primary cause for the war. Tragically, all five of her sons were slaughtered in the post-war night raid.",
    image: 'https://picsum.photos/seed/draupadi/400/500',
  }
];