import { Character } from './types';

// This character data has been carefully curated based on the provided PDF document,
// simulating a Gemini API call with a prompt to extract structured information
// with a temperature of 0 to avoid hallucinations and ensure factual adherence.

export const CHARACTERS: Character[] = [
  {
    name: 'Krishna',
    clan: 'Vrishni',
    role: 'A divine catalyst and advisor to the Pandavas.',
    description: "An incarnation of Vishnu, his strategic wisdom is pivotal. He delivers the Bhagavad Gita to Arjuna and urges him to strike the vulnerable Karna, reminding him that the rules of war were already broken by the enemy in the killing of Abhimanyu.",
    image: 'https://picsum.photos/seed/krishna/400/500',
  },
  {
    name: 'Arjuna',
    clan: 'Pandava',
    role: 'The great Pandava archer and central hero of the Bhagavad Gita.',
    description: 'One of the five Pandava brothers, son of Indra. He receives the profound discourse of the Bhagavad Gita from Krishna. His killing of Karna, while his enemy was vulnerable, underscores how even heroes can be undone by unrighteous circumstances.',
    image: 'https://picsum.photos/seed/arjuna/400/500',
  },
  {
    name: 'Yudhishthira',
    clan: 'Pandava',
    role: 'The eldest Pandava, the embodiment of dharma.',
    description: "Son of the god Dharma, known for his righteousness. His adherence to truth is tested when he utters a half-truth about the death of 'Ashwatthama' (an elephant), which leads Drona to lay down his arms. This act shows the war's corrupting influence.",
    image: 'https://picsum.photos/seed/yudhishthira/400/500',
  },
   {
    name: 'Bhima',
    clan: 'Pandava',
    role: 'The second Pandava, known for his immense strength and wrath.',
    description: "Son of the wind-god Vayu. After Draupadi's humiliation, he takes a terrible vow to drink Dushasana's blood and kill all 100 Kaurava brothers, a vow he systematically fulfills. His final mace duel with Duryodhana seals the Pandavas' victory.",
    image: 'https://picsum.photos/seed/bhima/400/500',
  },
  {
    name: 'Duryodhana',
    clan: 'Kaurava',
    role: 'The eldest Kaurava and primary antagonist, driven by jealousy.',
    description: "The eldest of Dhritarashtra's 100 sons. His unwavering arrogance and jealousy drive the conflict. He is an exceptional mace fighter, but is ultimately killed by Bhima in their final duel on the 18th day of the war.",
    image: 'https://picsum.photos/seed/duryodhana/400/500',
  },
  {
    name: 'Dushasana',
    clan: 'Kaurava',
    role: 'The infamous brother who sealed the Kauravas\' fate.',
    description: 'The second Kaurava brother, remembered for his role in the public disrobing of Draupadi. This infamous event was the direct cause of Bhima\'s oath to avenge the insult by drinking Dushasana\'s blood. He was brutally killed by Bhima, who fulfilled his vow.',
    image: 'https://picsum.photos/seed/dushasana/400/500',
  },
  {
    name: 'Karna',
    clan: 'Kaurava (allied)',
    role: 'The tragic hero, hidden son of Kunti, and loyal friend to Duryodhana.',
    description: "The eldest half-brother of the Pandavas. He served as the commander-in-chief of the Kaurava army on the 16th and 17th days. He is killed by Arjuna when his chariot wheel becomes stuck in the mud due to a curse, leaving him vulnerable.",
    image: 'https://picsum.photos/seed/karna/400/500',
  },
  {
    name: 'Abhimanyu',
    clan: 'Pandava',
    role: 'The tragic prince and Arjuna\'s valiant son.',
    description: 'The son of Arjuna and Subhadra. A profoundly skilled archer, he single-handedly broke into the formidable Chakravyuha formation on the 13th day of the war. He was trapped inside and killed by multiple warriors collectively, violating the established rules of warfare.',
    image: 'https://picsum.photos/seed/abhimanyu/400/500',
  },
  {
    name: 'Ghatotkacha',
    clan: 'Pandava (ally)',
    role: 'The powerful half-demon son of Bhima.',
    description: "Son of Bhima and the Rakshasi Hidimbi. His strength and magical powers peaked at night. On the 14th night, his rampage forced Karna to use his one-time divine weapon, the Vasavi Shakti, to kill him, saving Arjuna from the same fate.",
    image: 'https://picsum.photos/seed/ghatotkacha/400/500',
  },
  {
    name: 'Bhishma',
    clan: 'Kuru',
    role: 'The grandsire of the Kuru dynasty, bound by a vow of service.',
    description: 'The first commander-in-chief of the Kaurava army. The Pandavas defeated him on Day 10 by using Shikhandi as a shield. He fell, pierced by countless arrows, and rested on a "bed of arrows" for 58 days before willingly leaving his body.',
    image: 'https://picsum.photos/seed/bhishma/400/500',
  },
  {
    name: 'Drona',
    clan: 'Kuru (advisor)',
    role: 'The revered martial arts teacher to both the Pandavas and Kauravas.',
    description: 'The royal preceptor and second Kaurava commander. Heartbroken by false news of his son\'s death, he laid down his weapons and entered a state of meditation, at which point he was beheaded by Dhrishtadyumna, fulfilling a prophecy.',
    image: 'https://picsum.photos/seed/drona/400/500',
  },
  {
    name: 'Ashwatthama',
    clan: 'Kaurava (ally)',
    role: 'The vengeful survivor and son of Drona.',
    description: "Enraged by his father's deceptive death, he retaliated in a brutal night raid, slaughtering the remaining Pandava forces, including the five Upapandavas. As an immortal, he is one of the few Kaurava-allied warriors to survive the war.",
    image: 'https://picsum.photos/seed/ashwatthama/400/500',
  },
  {
    name: 'Shakuni',
    clan: 'Gandhara',
    role: 'The cunning maternal uncle of the Kauravas and master manipulator.',
    description: "The mastermind behind the Kauravas' schemes. He engineered the rigged game of dice that led to the Pandavas' humiliation and exile, ultimately instigating the Kurukshetra War. He was killed during the war.",
    image: 'https://picsum.photos/seed/shakuni/400/500',
  },
  {
    name: 'Dhrishtadyumna',
    clan: 'Panchala',
    role: 'The fated commander of the Pandava army.',
    description: "Son of King Drupada, born from a fire-sacrifice to kill Drona. He fulfills this destiny on Day 15. He was later killed in an act of vengeance by Ashwatthama, who brutally beat him to death in the post-war night raid.",
    image: 'https://picsum.photos/seed/dhrishtadyumna/400/500',
  },
  {
    name: 'Yuyutsu',
    clan: 'Kaurava (defected)',
    role: 'The righteous brother who chose dharma over family.',
    description: "The son of Dhritarashtra and a Vaishya servant. Unlike his Kaurava half-brothers, he recognized their unrighteousness and chose to join the Pandava side. This singular act of moral courage made him one of the war's very few survivors.",
    image: 'https://picsum.photos/seed/yuyutsu/400/500',
  },
  {
    name: 'Kripacharya',
    clan: 'Kuru (Guru)',
    role: 'The royal guru and a survivor of the war.',
    description: "A revered teacher and the brother-in-law of Drona. He fought for the Kauravas out of loyalty to the throne. Along with Ashwatthama and Kritavarma, he was one of the only three major surviving warriors on the Kaurava side.",
    image: 'https://picsum.photos/seed/kripacharya/400/500',
  },
  {
    name: 'Jayadratha',
    clan: 'Sindhu',
    role: 'The King of Sindhu and a key Kaurava ally.',
    description: "He played a crucial role in Abhimanyu's death by single-handedly preventing the other Pandavas from entering the Chakravyuha formation. This act sealed his fate; Arjuna vowed to kill him, a feat accomplished after Krishna created a false sunset to expose him.",
    image: 'https://picsum.photos/seed/jayadratha/400/500',
  },
  {
    name: 'Bhagadatta',
    clan: 'Pragjyotisha',
    role: 'The formidable king and elephant warrior.',
    description: "The King of Pragjyotisha, known for his formidable combat skills while riding his elephant, Supratika. He was a key figure on the Kaurava side and was killed by Arjuna on the 12th day of the war after a fierce battle.",
    image: 'https://picsum.photos/seed/bhagadatta/400/500',
  },
  {
    name: 'Drupada',
    clan: 'Panchala',
    role: 'The King of Panchala and a key Pandava ally.',
    description: "Father of Dhrishtadyumna, Draupadi, and Shikhandi. His long-standing rivalry with Drona was a key factor in the war's alliances. He fought fiercely alongside the Pandavas and was ultimately killed by his old rival, Drona.",
    image: 'https://picsum.photos/seed/drupada/400/500',
  },
  {
    name: 'Shikhandi',
    clan: 'Panchala',
    role: 'The warrior destined to cause Bhishma\'s downfall.',
    description: "The son of King Drupada, born as a woman in a previous life. Knowing that Bhishma would not raise a weapon against a former woman, Arjuna used him as a shield to defeat the grandsire. Shikhandi fulfilled his destiny but also perished in the war.",
    image: 'https://picsum.photos/seed/shikhandi/400/500',
  },
  {
    name: 'King Virata',
    clan: 'Matsya',
    role: 'The King of Matsya who sheltered the Pandavas.',
    description: "The king who provided refuge to the Pandavas during their year of incognito exile. In gratitude, he and his sons fought alongside the Pandavas. All perished in the war, with Virata himself being killed by Dronacharya.",
    image: 'https://picsum.photos/seed/virata/400/500',
  },
  {
    name: 'Draupadi',
    clan: 'Panchala',
    role: 'The shared wife of the Pandavas and a catalyst for the war.',
    description: "Born from a sacrificial fire, Draupadi is a strong and fiery princess. Her public humiliation by Dushasana in the Kaurava court is a pivotal moment that becomes a primary cause for the war. Tragically, all five of her sons were slaughtered in the post-war night raid.",
    image: 'https://picsum.photos/seed/draupadi/400/500',
  },
  {
    name: 'Sage Vyasa',
    clan: 'Kuru (Progenitor)',
    role: 'The epic\'s author and progenitor of the Kuru princes.',
    description: 'The son of Satyavati and the sage Parashara. To prevent the Kuru line from ending, he fathered Dhritarashtra and Pandu with his deceased half-brother\'s widows. He is the narrator and a key guiding figure throughout the epic.',
    image: 'https://picsum.photos/seed/vyasa/400/500',
  },
  {
    name: 'Dhritarashtra',
    clan: 'Kuru',
    role: 'The blind king of Hastinapura.',
    description: 'The father of the one hundred Kauravas. Born blind, he was denied the throne in his youth in favor of his younger brother Pandu. His deep, often misguided, affection for his son Duryodhana was a primary cause of the war.',
    image: 'https://picsum.photos/seed/dhritarashtra/400/500',
  },
  {
    name: 'Gandhari',
    clan: 'Kuru (by marriage)',
    role: 'The devoted wife of Dhritarashtra.',
    description: 'Mother of the Kauravas. Upon learning her betrothed, Dhritarashtra, was blind, she chose to blindfold herself for the rest of her life in an act of marital solidarity and sacrifice.',
    image: 'https://picsum.photos/seed/gandhari/400/500',
  },
  {
    name: 'Pandu',
    clan: 'Kuru',
    role: 'The father of the Pandavas.',
    description: 'Younger brother of Dhritarashtra. He was a great warrior and ruled as king, but was cursed to die if he ever approached his wives. The five Pandavas were thus born through a divine boon granted to his wife Kunti.',
    image: 'https://picsum.photos/seed/pandu/400/500',
  },
  {
    name: 'Kunti',
    clan: 'Pandava (by marriage)',
    role: 'The mother of three Pandavas and Karna.',
    description: 'The first wife of Pandu. She possessed a divine mantra that allowed her to invoke gods to father her children, resulting in the births of Yudhishthira, Bhima, and Arjuna. She was also the mother of Karna, whom she abandoned at birth.',
    image: 'https://picsum.photos/seed/kunti/400/500',
  },
  {
    name: 'Madri',
    clan: 'Pandava (by marriage)',
    role: 'The second wife of Pandu.',
    description: 'The mother of the twins, Nakula and Sahadeva. She shared Kunti\'s divine boon to give birth to her sons. She committed sati, joining her husband on his funeral pyre.',
    image: 'https://picsum.photos/seed/madri/400/500',
  },
  {
    name: 'Hidimbi',
    clan: 'Rakshasa',
    role: 'A Rakshasi wife of Bhima.',
    description: 'A demoness who fell in love with Bhima and married him. She was the mother of the powerful and loyal Ghatotkacha, who became a formidable asset to the Pandavas during the war.',
    image: 'https://picsum.photos/seed/hidimbi/400/500',
  },
  {
    name: 'Uttara',
    clan: 'Matsya',
    role: 'Wife of Abhimanyu and mother of the heir.',
    description: 'The princess of the Matsya Kingdom. She married Abhimanyu, and their son, Parikshit, was the sole heir to survive the war and continue the Kuru dynasty after being saved by Krishna.',
    image: 'https://picsum.photos/seed/uttara/400/500',
  },
  {
    name: 'Parikshit',
    clan: 'Kuru',
    role: 'The sole surviving heir of the Kuru dynasty.',
    description: 'The posthumous son of Abhimanyu and Uttara. As the grandson of Arjuna, he inherited the throne of Hastinapura. He was saved from a celestial weapon while still in the womb by Krishna, ensuring the continuation of the lineage.',
    image: 'https://picsum.photos/seed/parikshit/400/500',
  },
  {
    name: 'Iravan',
    clan: 'Naga/Pandava',
    role: 'The son of Arjuna and Uloopi.',
    description: 'A valiant warrior born to Arjuna and the Naga princess Uloopi. He fought bravely for the Pandavas and sacrificed himself heroically on the eighth day of the war to ensure their victory.',
    image: 'https://picsum.photos/seed/iravan/400/500',
  },
  {
    name: 'Chitrangada (Wife of Arjuna)',
    clan: 'Manipura',
    role: 'A warrior princess and wife of Arjuna.',
    description: 'The princess of Manipura who married Arjuna during his exile. She was a skilled warrior in her own right and the mother of their son, Babruvahana.',
    image: 'https://picsum.photos/seed/chitrangada_wife/400/500',
  },
  {
    name: 'Babruvahana',
    clan: 'Manipura/Pandava',
    role: 'The son of Arjuna and Chitrangada.',
    description: 'Raised in Manipura, he later came into conflict with his own father, Arjuna, during a conquest. He defeated and killed Arjuna, but later revived him with a celestial gem procured by Uloopi.',
    image: 'https://picsum.photos/seed/babruvahana/400/500',
  },
  {
    name: 'Prativindhya',
    clan: 'Pandava',
    role: 'Son of Yudhishthira & Draupadi.',
    description: 'The eldest of the Upapandavas (the five sons of the Pandavas and Draupadi). He was a valiant warrior who fought in the Kurukshetra War and was tragically killed in his sleep by Ashwatthama during the vengeful night raid.',
    image: 'https://picsum.photos/seed/prativindhya/400/500',
  },
  {
    name: 'Sutasoma',
    clan: 'Pandava',
    role: 'Son of Bhima & Draupadi.',
    description: 'One of the Upapandavas. He was known for his strength and prowess, fought bravely during the war, and was tragically killed in his sleep by Ashwatthama\'s cowardly night raid.',
    image: 'https://picsum.photos/seed/sutasoma/400/500',
  },
  {
    name: 'Shrutakarma',
    clan: 'Pandava',
    role: 'Son of Arjuna & Draupadi.',
    description: 'One of the Upapandavas. A skilled warrior like his father, he fought in the war and met his end during Ashwatthama\'s slaughter of the sleeping Pandava army after the 18th day.',
    image: 'https://picsum.photos/seed/shrutakarma/400/500',
  },
  {
    name: 'Shatanika',
    clan: 'Pandava',
    role: 'Son of Nakula & Draupadi.',
    description: 'One of the Upapandavas. He fought alongside his brothers and father in the war. He was among the many warriors slain by Ashwatthama in the treacherous post-war night attack.',
    image: 'https://picsum.photos/seed/shatanika/400/500',
  },
  {
    name: 'Shrutasena',
    clan: 'Pandava',
    role: 'Son of Sahadeva & Draupadi.',
    description: 'The youngest of the Upapandavas. He participated in the great war and was one of the final victims of the conflict, murdered in his sleep by Ashwatthama.',
    image: 'https://picsum.photos/seed/shrutasena/400/500',
  },
  {
    name: 'Yaudheya',
    clan: 'Pandava',
    role: 'Son of Yudhishthira & Devika.',
    description: 'A son of Yudhishthira from his wife Devika. He was one of the many sons of the Pandavas who perished in the devastating Kurukshetra War.',
    image: 'https://picsum.photos/seed/yaudheya/400/500',
  },
  {
    name: 'Sarvaga',
    clan: 'Pandava',
    role: 'Son of Bhima & Valandhara.',
    description: 'A son of Bhima and his wife Valandhara. He fought in the war and, like most of his generation, did not survive the conflict.',
    image: 'https://picsum.photos/seed/sarvaga/400/500',
  },
  {
    name: 'Niramitra',
    clan: 'Pandava',
    role: 'Son of Nakula & Karenumati.',
    description: 'A son of Nakula from his wife Karenumati. He was a warrior who fought on the Pandava side and was killed during the 18-day war.',
    image: 'https://picsum.photos/seed/niramitra/400/500',
  },
  {
    name: 'Suhotra',
    clan: 'Pandava',
    role: 'Son of Sahadeva & Vijaya.',
    description: 'A son of Sahadeva and his wife Vijaya. He joined his family in the great war and was among the countless warriors who fell in battle.',
    image: 'https://picsum.photos/seed/suhotra/400/500',
  },
  {
    name: 'Vaishya Servant',
    clan: 'Kuru',
    role: 'Mother of Yuyutsu.',
    description: 'A serving woman to Queen Gandhari. She was the mother of Yuyutsu, the only one of Dhritarashtra\'s sons to recognize the Kauravas\' unrighteousness and survive the war.',
    image: 'https://picsum.photos/seed/vaishya/400/500',
  },
  {
    name: 'King Kuru',
    clan: 'Kuru',
    role: 'Founder of the Kuru Dynasty.',
    description: 'The ancient and revered ancestor from whom the Kuru dynasty, including both the Pandavas and Kauravas, derives its name. His legacy established the kingdom and the lineage.',
    image: 'https://picsum.photos/seed/kuru/400/500',
  },
  {
    name: 'King Shantanu',
    clan: 'Kuru',
    role: 'The Kuru king and father of Bhishma.',
    description: 'A pivotal king of the Kuru dynasty whose marriages to Ganga and Satyavati set the stage for the complex succession crisis that followed, leading to Bhishma\'s great vow.',
    image: 'https://picsum.photos/seed/shantanu/400/500',
  },
  {
    name: 'Ganga',
    clan: 'Divine',
    role: 'The river goddess and mother of Bhishma.',
    description: 'A celestial goddess who married King Shantanu. She was the mother of Bhishma, the eighth of her sons, whom she left on earth to fulfill his destiny.',
    image: 'https://picsum.photos/seed/ganga/400/500',
  },
  {
    name: 'Satyavati',
    clan: 'Kuru (by marriage)',
    role: 'The queen of Shantanu and great-grandmother of the warring princes.',
    description: 'King Shantanu\'s second wife. Her desire for her sons to inherit the throne led to Bhishma\'s vow of celibacy. She is the mother of Chitrangada and Vichitravirya, and grandmother of Dhritarashtra and Pandu through Vyasa.',
    image: 'https://picsum.photos/seed/satyavati/400/500',
  },
  {
    name: 'Chitrangada & Vichitravirya',
    clan: 'Kuru',
    role: 'The short-lived sons of Shantanu and Satyavati.',
    description: 'The heirs to the Kuru throne after Shantanu. Chitrangada was killed in battle, and Vichitravirya died childless, creating a succession crisis that was resolved by the sage Vyasa.',
    image: 'https://picsum.photos/seed/vichitravirya/400/500',
  },
  {
    name: 'Vasudeva',
    clan: 'Vrishni (Yadava)',
    role: 'Father of Krishna and a Yadava chieftain.',
    description: 'A nobleman of the Yadava clan and the father of Krishna and Balarama. He was the brother of Kunti, connecting the Yadavas and the Pandavas by blood.',
    image: 'https://picsum.photos/seed/vasudeva/400/500',
  },
  {
    name: 'Devaki',
    clan: 'Vrishni (Yadava)',
    role: 'Mother of Krishna.',
    description: 'Wife of Vasudeva and mother of Krishna. She was imprisoned by her tyrannical brother Kamsa, who feared a prophecy that her eighth child would kill him.',
    image: 'https://picsum.photos/seed/devaki/400/500',
  },
  {
    name: 'Balarama',
    clan: 'Vrishni (Yadava)',
    role: 'Krishna\'s elder brother and a mighty warrior.',
    description: 'Known for his immense strength and mastery of the mace. Unlike Krishna, he remained neutral in the Kurukshetra War, as he held affection for both the Pandavas and Kauravas.',
    image: 'https://picsum.photos/seed/balarama/400/500',
  },
  {
    name: 'Subhadra',
    clan: 'Vrishni (Yadava)',
    role: 'Sister of Krishna and wife of Arjuna.',
    description: 'The beloved sister of Krishna and Balarama. Her marriage to Arjuna solidified the powerful alliance between the Pandavas and the Yadavas. She was the mother of the tragic hero Abhimanyu and grandmother to Parikshit, the sole heir to the Kuru throne.',
    image: 'https://picsum.photos/seed/subhadra/400/500',
  },
  {
    name: 'Rohini',
    clan: 'Vrishni (Yadava)',
    role: 'A wife of Vasudeva.',
    description: 'One of the wives of Vasudeva. She raised Balarama and was also the mother of Subhadra, playing a crucial maternal role in the Yadava household.',
    image: 'https://picsum.photos/seed/rohini/400/500',
  },
  {
    name: 'Revati',
    clan: 'Anarta',
    role: 'Wife of Balarama.',
    description: 'The princess of the Anarta Kingdom and the wife of Balarama. Their story involves time dilation, as she was from a much earlier era, and Balarama used his plough to resize her to fit his stature.',
    image: 'https://picsum.photos/seed/revati/400/500',
  },
  {
    name: 'Satyabhama',
    clan: 'Vrishni (Yadava)',
    role: 'A principal wife of Krishna.',
    description: 'Another of Krishna\'s chief wives, known for her strong will and pride. She is often depicted alongside Rukmini and is an incarnation of Bhudevi, the earth goddess.',
    image: 'https://picsum.photos/seed/satyabhama/400/500',
  },
  {
    name: 'Pradyumna',
    clan: 'Vrishni (Yadava)',
    role: 'Son of Krishna and Rukmini.',
    description: 'The eldest son of Krishna and Rukmini, considered an incarnation of Kamadeva, the god of love. He was a formidable warrior who played a significant role in the Yadava clan\'s battles.',
    image: 'https://picsum.photos/seed/pradyumna/400/500',
  },
  {
    name: 'Rukmini',
    clan: 'Vrishni (Yadava)',
    role: 'The chief consort of Krishna.',
    description: 'The principal wife of Krishna. She is revered as an incarnation of the goddess Lakshmi and is a central figure in Krishna\'s life and dynasty.',
    image: 'https://picsum.photos/seed/rukmini/400/500',
  },
  {
    name: 'Devika',
    clan: 'Shivi',
    role: 'Wife of Yudhishthira.',
    description: 'One of the wives of Yudhishthira and the princess of the Shivi kingdom. She was the mother of his son, Yaudheya.',
    image: 'https://picsum.photos/seed/devika/400/500',
  },
  {
    name: 'Karenumati',
    clan: 'Chedi',
    role: 'Wife of Nakula.',
    description: 'A princess of the Chedi Kingdom and one of Nakula\'s wives. She was the mother of his son, Niramitra.',
    image: 'https://picsum.photos/seed/karenumati/400/500',
  },
  {
    name: 'Vijaya',
    clan: 'Madra',
    role: 'Wife of Sahadeva.',
    description: 'A princess of the Madra Kingdom and one of Sahadeva\'s wives. She was the mother of his son, Suhotra.',
    image: 'https://picsum.photos/seed/vijaya/400/500',
  },
  {
    name: 'Valandhara',
    clan: 'Kashi',
    role: 'Wife of Bhima.',
    description: 'A princess of the Kashi Kingdom and one of Bhima\'s wives. She was the mother of his son, Sarvaga.',
    image: 'https://picsum.photos/seed/valandhara/400/500',
  },
  {
    name: 'Uloopi',
    clan: 'Naga',
    role: 'A Naga princess and wife of Arjuna.',
    description: 'A powerful Naga princess who married Arjuna during his exile. She was the mother of his son Iravan and later played a crucial role in reviving Arjuna after he was killed by his own son, Babruvahana.',
    image: 'https://picsum.photos/seed/uloopi/400/500',
  }
];